### ISSUE TITLE
Local Version

### ISSUE THREAD

**Issue by marat569** [e7d/gamepad-viewer#3]
Hey, I'm not a programmer.

Would it be possible to somehow get this running locally. I know you'd have to modify some ajax and redirect stuff; but I'd love to have a program that lasts "forever" becuse I can just point to a local index.html (or whatever)

Note: Not a webserver version, but like I can literally just point OBS to some html file on my desktop and it will work, or just double click the .html file.

Thank you <3

**Comment by albertlopes** [comment]
@marat569 You problably solved this already, but for anyone trying to run localy is very easy.
1 - Go to the nginx website: http://nginx.org/en/download.html download the last version and extract
2 - Copy the content of this repository in the folder html of nginx, be sure to overwrite the index.html file. 
3 - Run nginx (assuming it is windows just double click nginx.exe) 
4 - Open a browser and navigate to http://localhost:80

That is it. I'd also recommed to create 2 batch files, one to start and another to kill nginx because its a console server that runs on background, you can use "start nginx.exe" to run and "nginx.exe -s quit" to close.
